# Train-Test Splitting: Behaivor

- Non Suffle
- Suffle
- Suffle + Stratify

In [9]:
%matplotlib inline
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
from sklearn import datasets
from sklearn.model_selection import train_test_split

## load data

In [7]:
X, y = datasets.load_iris(return_X_y=True)
X = pd.DataFrame(data=X, columns=['Sepal length', 'Sepal width', 'Petal length', 'Petal width'])
y = pd.Series(y).map({0: 'Setosa', 1: 'Versicolor', 2: 'Virginica'})
X.shape, y.shape, np.unique(y, return_counts=True)

((150, 4),
 (150,),
 (array(['Setosa', 'Versicolor', 'Virginica'], dtype=object),
  array([50, 50, 50])))

### train test split: Non Random

In [18]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, shuffle = False)

In [19]:
print(y_train.shape, y_test.shape)

(100,) (50,)


In [20]:
y_train.index, y_test.index

(Int64Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
             17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
             34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
             51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
             68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
             85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
            dtype='int64'),
 Int64Index([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
             113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
             126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
             139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149],
            dtype='int64'))

In [21]:
np.unique(y_train, return_counts=True), np.unique(y_test, return_counts=True)

((array(['Setosa', 'Versicolor'], dtype=object), array([50, 50])),
 (array(['Virginica'], dtype=object), array([50])))

### train test split: Random

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42, shuffle = True)

In [14]:
print(y_train.shape, y_test.shape)

(100,) (50,)


In [15]:
y_train.index, y_test.index

(Int64Index([ 96, 105,  66,   0, 122,  67,  28,  40,  44,  60, 123,  24,  25,
              23,  94,  39,  95, 117,  47,  97, 113,  33, 138, 101,  62,  84,
             148,  53,   5,  93, 111,  49,  35,  80,  77,  34, 114,   7,  43,
              70,  98, 120,  83, 134, 135,  89,   8,  13, 119, 125,   3,  17,
              38,  72, 136,   6, 112, 100,   2,  63,  54, 126,  50, 115,  46,
             139,  61, 147,  79,  59,  91,  41,  58,  90,  48,  88, 107, 124,
              21,  57, 144, 129,  37, 140,   1,  52, 130, 103,  99, 116,  87,
              74, 121, 149,  20,  71, 106,  14,  92, 102],
            dtype='int64'),
 Int64Index([ 73,  18, 118,  78,  76,  31,  64, 141,  68,  82, 110,  12,  36,
               9,  19,  56, 104,  69,  55, 132,  29, 127,  26, 128, 131, 145,
             108, 143,  45,  30,  22,  15,  65,  11,  42, 146,  51,  27,   4,
              32, 142,  85,  86,  16,  10,  81, 133, 137,  75, 109],
            dtype='int64'))

In [17]:
np.unique(y_train, return_counts=True), np.unique(y_test, return_counts=True)

((array(['Setosa', 'Versicolor', 'Virginica'], dtype=object),
  array([31, 35, 34])),
 (array(['Setosa', 'Versicolor', 'Virginica'], dtype=object),
  array([19, 15, 16])))

### train test split: Random (mandatory) + Stratify

In [25]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42, shuffle = True, stratify = y)

In [26]:
print(y_train.shape, y_test.shape)

(100,) (50,)


In [27]:
y_train.index, y_test.index

(Int64Index([136,  17, 142,  59,   6,  32,  15, 137,  30,  34,  54,   9,  98,
              62, 128, 149,  33,   4, 102,  44, 114,  48,  24, 131,  37,  58,
             126,  89,  13,  90,  12, 144,  80, 135,  97,  25, 113,  19, 115,
              29,  64,  79,  16, 139,  81,  75,  36, 101,  70, 117,  40,  92,
               8, 100,  74,  71,  83,  73,  87,  65, 121,  76, 130, 123,  26,
             110,  82,  52, 112,   3, 118, 129, 105,  46, 119,  11,  43, 109,
             103, 146,  27,  50, 120, 125,  31,  72,  91,  68,  95,  61,   0,
             124,  94, 143,   5,  49,  86,  45,  60,  47],
            dtype='int64'),
 Int64Index([133,  56,   7,  67, 107,  57,  55,  18,  66,  53,  42,  14,  23,
              39,  10, 132, 138,  69, 122,  99, 147,  88,   2, 116,  22, 104,
             140,  35,  20, 148, 111, 141,  21,  84,  28,  41, 145,  96,  77,
              85,  63,  93,  38,   1, 134,  78, 108, 106,  51, 127],
            dtype='int64'))

In [29]:
np.unique(y_train, return_counts=True), np.unique(y_test, return_counts=True)

((array(['Setosa', 'Versicolor', 'Virginica'], dtype=object),
  array([34, 33, 33])),
 (array(['Setosa', 'Versicolor', 'Virginica'], dtype=object),
  array([16, 17, 17])))